add_newline = true

format = """\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $golang\
  $haskell\
  $java\
  $nodejs\
  $php\
  $python\
  $ruby\
  $rust\
  $cmd_duration\
  $line_break\
  $jobs\
  $character\
  """
